//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class NetworkPackage
{
	public static int Width{get{return 256;}}

	public static int Height{get{return 256;}}

	public static int Size{get{return 40000;}}

}


